set(vtkPython_LOADED 1)
set(vtkPython_DEPENDS "vtkCommonCore")
set(vtkPython_LIBRARIES "/usr/lib/x86_64-linux-gnu/libpython2.7.so.1")
set(vtkPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/paraview-5.6;/usr/include/python2.7")
set(vtkPython_LIBRARY_DIRS "")
set(vtkPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/lib")
set(vtkPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkPythonHierarchy.txt")
set(vtkPython_KIT "")
set(vtkPython_TARGETS_FILE "")
set(vtkPython_EXCLUDE_FROM_WRAPPING 1)
set(VTK_PYTHONPATH "../debian/paraviewopenfoam56/opt/paraviewopenfoam56/lib/python2.7/site-packages")

